spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/FamilyDB
    password: postgre
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'